# environment_cpu.yml
name: sc_gat_cpu
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch=2.0.0
  - torchvision
  - torchaudio
  - pytorch-geometric=2.3.0
  - cpuonly   
  - torch-scatter=2.1.0
  - torch-sparse=0.6.16
  - torch-cluster=1.6.0
  - torch-spline-conv=1.2.0
  - scanpy=1.9.0
  - anndata=0.8.0
  - scikit-learn=1.2.0
  - numpy=1.23.0
  - scipy=1.9.0
  - pandas=1.5.0
  - h5py=3.7.0
  - tables=3.7.0
  - matplotlib=3.6.0
  - seaborn=0.12.0
  - tqdm=4.64.0
  - pyyaml=6.0